### ISSUE TITLE
Comparing IndividualUriValues in ModelObject#listsEquivalent may be broken?

### ISSUE THREAD

**Issue by nicoweidner** [spdx/Spdx-Java-Library#108]
While reading code, I noticed [this part of the list comparison](https://github.com/spdx/Spdx-Java-Library/blob/5d9fbc5aed6d244921ae392bb8840066eba08fd7/src/main/java/org/spdx/library/model/ModelObject.java#L942-L943) that seems weird to me. Here is my understanding of what's going on in general:
- we iterate over `list1`
- for each element, we try to find an element of `list2` that is equivalent
- if all elements have a corresponding match, the lists are equivalent, else inequivalent

Here is my issue with the `IndividualUriValue` case. Setup:
- we are in the case where `item instanceOf IndividualUriValue`
- we check whether `list2` contains `new SimpleUriValue((IndividualUriValue)item)`. Let's call this newly created instance `simpleUri`.
BUT:
- this will check whether `list2` contains any `element` satisfying `simpleUri.equals(element)`
- [the equals method on SimpleUriValue](https://github.com/spdx/Spdx-Java-Library/blob/5d9fbc5aed6d244921ae392bb8840066eba08fd7/src/main/java/org/spdx/library/model/SimpleUriValue.java#L94-L100) checks for class equality
- so if `element` is an instance of any class _except_ `SimpleUriValue` that implements `IndividualUriValue` (e.g. `ExternalSpdxElement` or `ReferenceType`), it will automatically be false

In case this is too abstract, I can try to come up with some minimal test cases, but may require some time.

Would love to hear your opinion @goneall to determine whether these are indeed bugs, or I am misunderstanding things. 

edit: Fixed the github links (now they link to specific commit instead of master to avoid getting out of sync when master changes)

The following additional issue was split off into https://github.com/spdx/Spdx-Java-Library/issues/114
> One additional issue I realized: Since we are checking for _equivalence_, not _equality_, we need to check equivalence in both directions. Else the `listsEquivalent` function is not symmetric.
Example: We have `list1 = [element11, element12]` and `list2 = [element21, element22]`, where `element11`, `element12` and `element21` are all equivalent but `element22` is completely different. The current algorithm would determine that `list1` is equivalent to `list2`, but `list2` is not equivalent to `list1`.

**Comment by goneall** [comment]
@nicoweidner Excellent catch - thanks for the review!

For most of the cases, the previous check for contains will return true even if it is a `IndividualUriValue`.  The extra check is primarily for external references (the enum implementations will likely be caught by the previous check).

I'm thinking we could fix this specific issue by changing the class check from:

```
if (!(comp instanceof SimpleUriValue)) {
```

to:

```
if (!(comp instanceof IndividualUriValue)) {
```

Looking further, some of the other implementations of `IndividualUriValue` should also override equals and hashcode to use the URI value so that it will be equal to a `SimpleUriValue` with the same URI.

Probably needs a bit more review and thought before committing the changes - let me know what you think.

As far as making the check symmetric - I agree this is a possible issue.

**Comment by goneall** [comment]
After thinking about this a bit more, I'm pretty convinced anything that implements `IndividualUriValue` should override equals/hashcode to use the URI value for equality.  The one exception is is the class implementing `IndividualUriValue` inherits from `ModelObject` which already overrides `equals` using the ID for equality.

@nicoweidner I'll create a PR with the changes for this.  If you have some time, feel free to tackle the symmetric issue.

**Comment by goneall** [comment]
@nicoweidner I created a PR to update equals for `IndividualUriValue`s.

In thinking about this some more, `SimpleUriValue` is typically only used when storing a property - when it is re-inflated back to a model object, it is typically cast to the appropriate type.  So this it will not likely cause a problem in practice.  That being said, it is a bug since the `SimpleUriValue` may be used for other purposes and the semantics of `IndividaulUriValue` should be equal if the URI's are equal.

I did go ahead and update the `ModelObject`s that implement `IndividualUriValue` to override equals.

The only implemenations of `IndividualUriValue` I did not update was the enumerations.  Since the `equals` method in enums are final, I could not override the method.

Please check out the PR and let me know if my logic and updates make sense.

**Comment by nicoweidner** [comment]
> For most of the cases, the previous check for contains will return true even if it is a IndividualUriValue. The extra check is primarily for external references (the enum implementations will likely be caught by the previous check).

Ah, you are right that the previous check should catch various `IndividualUriValue` implementations. I completely missed that when looking at the two lines about `IndividualUriValue` in isolation :sweat_smile: . In the end, it boils down to how the `equals` method works in each case. All enum implementations should be fine.

I will think about how the other cases behave. It probably makes more sense to comment directly on the PR since you already made changes there, so I will do that.
