### ISSUE TITLE
Cannot use ExternalExtractedLicenseInfo

### ISSUE THREAD

**Issue by nicoweidner** [spdx/Spdx-Java-Library#134]
Disclaimer: I don't have a good understanding of the "external" entities `ExternalExtractedLicenseInfo` and `ExternalSpdxElement`, but was rather following the code.

I tried to use a `ExternalExtractedLicenseInfo` in a document, adding it to the list of extractedLicenseInfos, and to serialize that doc to json. Then `doc.verify()` passes, but when trying to serialize to json, the error `Extracted License Infos not of type ExtractedLicensingInfo`. That feels wrong to me, since `ExternalExtractedLicenseInfo extends ExtractedLicenseInfo`.

A halfway complete test case: Here, `doc` is some minimal document. The error is thrown on the last line, when trying to serialize the document.
```
        var externalDocumentRef = doc.createExternalDocumentRef("DocumentRef-1", "externalDocUri", sha1Checksum);
        var externalLicenseInfo = new ExternalExtractedLicenseInfo(doc.getModelStore(), doc.getDocumentUri(), "DocumentRef-1:LicenseRef-XXX", doc.getCopyManager(), true);
        doc.setExternalDocumentRefs(List.of(externalDocumentRef));
        
        doc.setExtractedLicenseInfos(List.of(externalLicenseInfo));
        
        assertThat(doc.verify()).isEmpty();

        var serializer = new JacksonSerializer(new ObjectMapper(),
                MultiFormatStore.Format.JSON_PRETTY, MultiFormatStore.Verbose.COMPACT,
                doc.getModelStore());
        var jsonNode = serializer.docToJsonNode(doc.getDocumentUri());
```

**Comment by goneall** [comment]
@nicoweidner I made a PR #137 which refactors the `ExtractedLicenseInfo` and `ExternaExtractedLicenseInfo` to inherit from an `AbstractExtractedLicenseInfo` class.  

I also added some more documentation to the Javadocs which hopefully helps make this less confusing.

I don't think this will cause any incompatibilities since it would be very uncommon to have code using an `ExtractedLicenseInfo` class and expect an `ExternalExtractedLicenseInfo`.  Most implementations which use a class expecting either internal or external license infos would use `AnyLicenseInfo` or `SimpleLicensingInfo` superclasses.  That being said, it is possible this may break some code.

I didn't make any similar changes to the `SpdxElement` and it's subclasses.  Referencing `SpdxElement` directly would be very common, so introducing a new abstract class would likely be a breaking change.  I'm also thinking it is less of an issue since `SpdxElement` is an abstract class.

We could refactor these out when we move to a 3.0 release where breaking changes are allowed.

Let me know what you think.

**Comment by goneall** [comment]
@nicoweidner - Let me know if you think PR #137 helps solve this issue.  I'm planning on a new release of the library and trying to decide if this should be included.

**Comment by nicoweidner** [comment]
Sorry, too many things going on, this dropped off my radar :sweat_smile: . I'll go have a look now.
IIRC, I didn't even have a case using `SpdxElement`, in that case it was a purely theoretical concern. So I think it's fine to fix only the `ExtractedLicenseInfo` part for now

**Comment by goneall** [comment]
Thanks @nicoweidner for the reviews and comments!
