### ISSUE TITLE
Pre-release code: inconsistent behaviour between matchingStandardLicenseIds and matchingStandardLicenseIdsWithinText

### ISSUE THREAD

**Issue by pmonks** [spdx/Spdx-Java-Library#155]
Note: this issue references pre-release code in 1.1.5-SNAPSHOT.

It is my understanding that when `org.spdx.utility.compare.LicenseCompareHelper.matchingStandardLicenseIds()` produces a non-null / non-empty result on a given input, `org.spdx.utility.compare.LicenseCompareHelper.matchingStandardLicenseIdsWithinText()` should produce that same output (albeit in a single-entry list) for that same input, but that's not always happening.

For example I tested both methods with [this license text](https://raw.githubusercontent.com/commonmark/commonmark-java/main/LICENSE.txt), and the former (correctly) returns `"BSD-2-Clause"`, while the latter returns `null`.

Perhaps this should be fixed prior to the release of 1.1.5, and more unit tests added that compare the outputs of the latter method against the former, given the same (single license) input texts?

**Comment by goneall** [comment]
I did some debugging and the issue is there is a `var` tag in the template which will allow matching to a regular expression.  `var` tags are honored in the `matchingStandardLicenseIds()` but not in the regular expression building part of `matchingStandardLicenseIdsWithinText()`.

Turns out the regular expressions can be extracted from the templates rather easily, but it is a bit of a design change to pass this information to the method that builds the regex pattern.

I have an idea how to approach this.  If it works, I'll put in a pull request.

**Comment by goneall** [comment]
@pmonks  - I was able to fix the inconsistent behavior but it causes an issue where some of the license template matches never complete.  You can see my attempt in PR #156 

I believe the issue is that the resultant Regex is non-deterministic and creates a nearly infinite loop.

We may be able to fix this by parsing the regular expressions and appending the maximum number of characters after any `.*` and `.+` expression.

Currently the unit tests stall out on the gpl3 test which I commented out in the pull request.

**Comment by goneall** [comment]
I limited the regex searches, so I know they will eventually finish.  It did speed up some of the unit tests - but it is still very slow.  Going to look for some more optimizations.

**Comment by pmonks** [comment]
Yeah I ran into this issue with the `GPL-3.0` regex too, back when I was using the templates directly (before I found this library). I _suspect_ it's a catastrophic backtracking problem with that template's `<var>`s.
