### ISSUE TITLE
LicenseCompareHelper: EPL-2.0 license text published by Eclipse Foundation not recognised

### ISSUE THREAD

**Issue by pmonks** [spdx/Spdx-Java-Library#213]
The [license text for `EPL-2.0` published by the Eclipse Foundation](https://www.eclipse.org/org/documents/epl-2.0/EPL-2.0.txt) is not being recognised by `org.spdx.utility.compare.LicenseCompareHelper.isStandardLicenseWithinText()`.

Note: tested with Spdx-Java-Library v1.1.8.

**Comment by sdheh** [comment]
This is caused by an error in LicenseCompareHelper.nonOptionalTextToStartPattern. In the part of the pattern that matches the end, NORMALIZE_TOKENS is not used for normalization ("copyright" doesn't get replaced by "-c-"). I tried adding this normalization and it fixed this bug.

The fix is simple but I won't fix it myself because I've never contributed and it seems like it would be a bit complicated because I would need to get approval from my company.

**Comment by pmonks** [comment]
@sdheh thank you so much - this is incredibly helpful!  I'll take a look at the code now.

**Comment by goneall** [comment]
One of the reasons this is failing is the same `.{0,36000}` match issue documented in #214
