### ISSUE TITLE
How to get the SPDX Items by Id?

### ISSUE THREAD

**Issue by zhaolida98** [spdx/Spdx-Java-Library#75]
Hi, 
Currently, we are working on building an SPDX document from scratch. We referred to the example [here](https://github.com/spdx/tools-java/blob/50238d0ada8064116554db5378ea73332c8dc0f5/examples/org/spdx/examples/SimpleSpdxDocument.java). Everything goes fine until we need to refer to a package that has already been created. We do this because we construct the graph structure from top to bottom. From the example below, we want to refer to the dependencies A again (for adding relationships) when we find A is a dependency of C. This is common when a dependency is referred to multiple times. 
![image](https://user-images.githubusercontent.com/28668213/161731053-d88b4970-fd4b-4ffb-bb58-b837c18bcb87.png)
 But seems that we cannot do that directly. There is no function designed for retrieving the `SpdxItems` by `SpdxId` directly. Method `getItem()` is `protected` and we cannot access that. We only found a method called `getAllItems()`, but that is obviously too heavy for retrieving only one package item. Is there any similar functions that can do this?

**Comment by goneall** [comment]
Greetings – To create a model object for an existing package, simply create the package passing in the model store, copy manager, document URI and the ID of the package you want to reference.

 

For example: `SpdxPackage pkg = new SpdxPackage(modelStore, documentUri, spdxId, copyManager, false);`

 

I’ll create a new example for deseralizing existing documents and include some comments on how to access other element types (such as SpdxPackage or SpdxFile).  

 

Let me know if this answers your question.

 

From: NRYet ***@***.***> 
Sent: Tuesday, April 5, 2022 3:20 AM
To: spdx/Spdx-Java-Library ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [spdx/Spdx-Java-Library] How to get the SPDX Items by Id? (Issue #75)

 

Hi,
Currently, we are working on building an SPDX document from scratch. We referred to the example here <https://github.com/spdx/tools-java/blob/50238d0ada8064116554db5378ea73332c8dc0f5/examples/org/spdx/examples/SimpleSpdxDocument.java> . Everything goes fine until we need to refer to a package that has already been created. We do this because we construct the graph structure from top to bottom. From the example below, we want to refer to the dependencies A again (for adding relationships) when we find A is a dependency of C. This is common when a dependency is referred to multiple times.
 <https://user-images.githubusercontent.com/28668213/161731053-d88b4970-fd4b-4ffb-bb58-b837c18bcb87.png> 
But seems that we cannot do that directly. There is no function designed for retrieving the SpdxItems by SpdxId directly. Method getItem() is protected and we cannot access that. We only found a method called getAllItems(), but that is obviously too heavy for retrieving only one package item. Is there any similar functions that can do this?

**Comment by goneall** [comment]
I just added an [example for accessing an existing document](https://github.com/spdx/tools-java/blob/master/examples/org/spdx/examples/ExistingSpdxDocument.java) which should provide a few more hints on how to access existing elements.

**Comment by zhaolida98** [comment]
Thanks for the new example, it helps a lot. I really appreciate your fast response. 
One more question, I am adding relationships by the following format
```
Relationship relationship = pkg.createRelationship(relatedPkg, RelationshipType.DEPENDS_ON, "");
pkg.addRelationship(relationship);
```
I learn that from source code and give it a lot of tries. Am I on the right path? If so, I suggest you also add examples for creating relationships in [the example here](https://github.com/spdx/tools-java/blob/master/examples/org/spdx/examples/SimpleSpdxDocument.java). It may help other people still in confusing.

**Comment by goneall** [comment]
> Thanks for the new example, it helps a lot. I really appreciate your fast response. One more question, I am adding relationships by the following format
> 
> ```
> Relationship relationship = pkg.createRelationship(relatedPkg, RelationshipType.DEPENDS_ON, "");
> pkg.addRelationship(relationship);
> ```
> 
> I learn that from source code and give it a lot of tries. Am I on the right path? If so, I suggest you also add examples for creating relationships in [the example here](https://github.com/spdx/tools-java/blob/master/examples/org/spdx/examples/SimpleSpdxDocument.java). It may help other people still in confusing.

Yes - you are on the right path.  Good suggestion on adding to the examples.  Feel free to create a PR with updated examples or I'll try to get to it later this week.

**Comment by zhaolida98** [comment]
Hi, I created a pull request [here](https://github.com/spdx/tools-java/pull/55), please have a look.  

Also, I am wondering if we can any some self-defined properties to the spdx document? For example, we would like to keep the branch information for projects from github. We find nowhere to keep such information. Maybe they are not part of the standard, but we may need them in some situations. Is there a way to add them to the document?

**Comment by goneall** [comment]
@zhaolida98 Thanks for the PR!

There are 2 ways to add additional information to elements in the SPDX documents.  The preferred approach is to create an Annotation of type `OTHER` and put the information in the Annotation comment.

The other approach is to add the information in the `comment` property.

For Package Manager information, you can use the [External reference](https://spdx.github.io/spdx-spec/package-information/#721-external-reference-field) with `PACKAGE-MANAGER` type.  You can also include Github specific download including the branch information in the [Package download location](https://spdx.github.io/spdx-spec/package-information/#77-package-download-location-field) field.  The download location and external reference are commonly used to correlate vulnerabilities - so they are good fields to use if you have that information.
